services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: task_tracker_app_2
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: task_tracker_nginx_2
        ports:
            - "8092:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: task_tracker_db_2
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: laravel
        ports:
            - "33067:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: task_tracker_pma_2
        ports:
            - "8102:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
